# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Trevor Austin
email: mail@trevoraustin.com
description: >
  Trevor Austin turns data science workflows into enterprise software products
  at Civis Analytics. This page hosts his blog, talks, and a brief bio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://trevoraustin.com" # the base hostname & protocol for your site
twitter_username: trevaustin
github_username:  trevoraustin

# Build settings
markdown: kramdown
